name: Accessibility Tests

on:
  push:
    branches: [ ally ]
  pull_request:
    branches: [ ally ]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run accessibility tests
        run: npm run test:a11y
