name: Validate HTML

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Run html5validator
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install --no-cache-dir html5validator
      - run: html5validator --root src/
